package main;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos_Aguirre.
 */
public class Menu extends javax.swing.JFrame {
    private Arbol arbol;
    private Dibujo canvas;

    public Menu() {
        arbol = new Arbol();
        canvas = new Dibujo(arbol);
        initComponents();
        contenedor.add(canvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recorridos = new javax.swing.ButtonGroup();
        contenedor = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        entrada = new javax.swing.JTextField();
        lblRecorrido1 = new javax.swing.JLabel();
        lblAleatorios = new javax.swing.JLabel();
        btnAleatorios = new javax.swing.JButton();
        lblRecorrido2 = new javax.swing.JLabel();
        lblRecorrido3 = new javax.swing.JLabel();
        lblRecorrido4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblNiveles = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        contenedor.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaActionPerformed(evt);
            }
        });
        contenedor.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 121, -1));
        contenedor.add(lblRecorrido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 510, 20));
        contenedor.add(lblAleatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 180, 20));

        btnAleatorios.setText("Generar Aleatorios");
        btnAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatoriosActionPerformed(evt);
            }
        });
        contenedor.add(btnAleatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));
        contenedor.add(lblRecorrido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 530, 20));
        contenedor.add(lblRecorrido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 560, 20));
        contenedor.add(lblRecorrido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 560, 20));

        jLabel1.setText("Postorden:");
        contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Preorden:");
        contenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, -1, -1));

        jLabel3.setText("Niveles:");
        contenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel4.setText("Inorden:");
        contenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        contenedor.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, -1));

        lblNiveles.setColumns(20);
        lblNiveles.setRows(5);
        jScrollPane1.setViewportView(lblNiveles);

        contenedor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        getContentPane().add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 22, 1210, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if(entrada.getText().length()!=0){
            if(arbol.buscar(Integer.parseInt(entrada.getText()), arbol.getRaiz())== false){
                arbol.setArrayPreorden(new ArrayList());
               // arbol.setArrayInorden(new ArrayList());
               // arbol.setArrayPostOrden(new ArrayList());
              //  arbol.setArrayPorNiveles(new ArrayList());
                arbol.insertar(Integer.parseInt(entrada.getText()));
                canvas.setArbol(arbol);
                canvas.repaint();
                recorridos();
            }else{
                JOptionPane.showMessageDialog(null,entrada.getText()+" ya se encuentra en el arbol.");
            }
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(entrada.getText().length()!=0 ){
            arbol.setRaiz(arbol.eliminar(Integer.parseInt(entrada.getText()),arbol.getRaiz()));
            canvas.setArbol(arbol);
            canvas.repaint();
            recorridos();        
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void recorridos(){
     
        arbol.inOrden(arbol.getRaiz());
        String text="";
        // text=""+arbol.getArrayInorden();
        text="{"+arbol.getArreglo().substring(0,arbol.getArreglo().length()-1)+"}";
        arbol.setArreglo("");
        lblRecorrido1.setText(text); 
        
        arbol.preOrden(arbol.getRaiz());
        //text=""+arbol.getArrayPreorden();
        text="{"+arbol.getArreglo().substring(0,arbol.getArreglo().length()-1)+"}";
        arbol.setArreglo("");
        lblRecorrido2.setText(text); 
        
        arbol.posOrden(arbol.getRaiz());
        // text=""+arbol.getArrayPostOrden();
        text="{"+arbol.getArreglo().substring(0,arbol.getArreglo().length()-1)+"}";
        arbol.setArreglo("");
        lblRecorrido3.setText(text);  
        
        arbol.porNiveles(arbol.getRaiz());
        //text=""+arbol.getArrayPorNiveles();
        text="{"+arbol.getArreglo().substring(0,arbol.getArreglo().length()-1)+"}";
        arbol.setArreglo("");
        lblRecorrido4.setText(text); 
        
        lblNiveles.setText("");
        String niveles="";
        for(int i=0;i<arbol.getArrayPorNiveles().size();i++){
            niveles+=arbol.getArrayPorNiveles().get(i)+"\n";
        }
        lblNiveles.setText(niveles);
        arbol.resetContador();
        arbol.setArrayPorNiveles(new ArrayList());

    }
    
    
    private void btnAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatoriosActionPerformed
        arbol.setArrayPreorden(new ArrayList());
        // arbol.setArrayInorden(new ArrayList());
        // arbol.setArrayPostOrden(new ArrayList());
        arbol.setArrayPorNiveles(new ArrayList());
        ArrayList a = new ArrayList();
        int num = (int) (Math.random() * 99) + 1;
        for(int i=0; i<5;i++){
            a.add((int) (Math.random() * 99) + 1);
        }
        arbol.dibujarAleatorios(a);
        lblAleatorios.setText("Aleatorios: {"+a.get(0)+","+a.get(1)+","+a.get(2)+","+a.get(3)+","+a.get(4)+"}");
        canvas.setArbol(arbol);
        canvas.repaint();
        recorridos();
    }//GEN-LAST:event_btnAleatoriosActionPerformed

    private void entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAleatorios;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JTextField entrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAleatorios;
    private javax.swing.JTextArea lblNiveles;
    private javax.swing.JLabel lblRecorrido1;
    private javax.swing.JLabel lblRecorrido2;
    private javax.swing.JLabel lblRecorrido3;
    private javax.swing.JLabel lblRecorrido4;
    private javax.swing.ButtonGroup recorridos;
    // End of variables declaration//GEN-END:variables
}
